# Generated by Django 4.2 on 2024-06-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('audio', models.FileField(upload_to='uploaded/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
        migrations.CreateModel(
            name='STTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_result_key', models.CharField(max_length=120, unique=True)),
                ('stt_result_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('stt_result_script', models.TextField(blank=True, null=True)),
                ('stt_start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('stt_end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('audio_source_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stt_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stt_result',
                'managed': True,
            },
        ),
    ]
